CREATE TABLE [dbo].[Arriv_Det_Del] (
    [AD_ID]       INT             IDENTITY (1, 1) NOT NULL,
    [Min_POld]    INT             NULL,
    [Name]        VARCHAR (90)    NULL,
    [Hitag]       INT             NULL,
    [Cost]        DECIMAL (12, 5) NULL,
    [Price]       DECIMAL (12, 2) NULL,
    [Morn]        INT             NULL,
    [Summacost]   DECIMAL (12, 2) NULL,
    [Summaprice]  DECIMAL (12, 2) NULL,
    [DatePost]    DATETIME        NULL,
    [Sklad]       INT             NULL,
    [MinP]        INT             NULL,
    [Mpu]         INT             NULL,
    [Srokh]       DATETIME        NULL,
    [DateR]       DATETIME        NULL,
    [Country]     VARCHAR (15)    NULL,
    [NCountry]    INT             NULL,
    [Our_ID]      INT             NULL,
    [Barcode]     VARCHAR (20)    NULL,
    [Extra]       DECIMAL (8, 5)  NULL,
    [Nds]         FLOAT (53)      NULL,
    [Ngrp]        INT             NULL,
    [Gtd]         VARCHAR (23)    NULL,
    [Locked]      BIT             NULL,
    [FName]       VARCHAR (100)   NULL,
    [OnlyMinP]    BIT             NULL,
    [FlgWeight]   BIT             NULL,
    [MeasID]      INT             NULL,
    [WCost]       DECIMAL (12, 5) NULL,
    [WPrice]      DECIMAL (10, 2) NULL,
    [OnlyBase]    BIT             NULL,
    [Netto]       DECIMAL (10, 3) NULL,
    [Brutto]      DECIMAL (10, 3) NULL,
    [NewTov]      BIT             NULL,
    [RecID]       INT             NULL,
    [Sert_ID]     INT             NULL,
    [SkMan]       VARCHAR (30)    NULL,
    [GrMan]       VARCHAR (30)    NULL,
    [Weight]      DECIMAL (10, 3) NULL,
    [cname]       VARCHAR (50)    NULL,
    [BarCodeMinP] VARCHAR (20)    NULL,
    [Storage]     INT             NULL,
    [Tara]        INT             NULL,
    [Level]       INT             NULL,
    [Index]       INT             NULL,
    [NLine]       INT             NULL,
    [Depth]       INT             NULL,
    [Volum]       DECIMAL (12, 5) NULL,
    [AM_ID]       INT             NULL,
    CONSTRAINT [Arriv_Det_pk] PRIMARY KEY CLUSTERED ([AD_ID] ASC)
);

