CREATE TABLE [dbo].[Back_Tomorrow_nc_Del] (
    [DatNom]       INT             NOT NULL,
    [ND]           DATETIME        NULL,
    [B_ID]         INT             NOT NULL,
    [Fam]          VARCHAR (35)    NULL,
    [TM]           CHAR (8)        NULL,
    [Op]           INT             NULL,
    [SP]           MONEY           NOT NULL,
    [SC]           MONEY           NOT NULL,
    [Extra]        DECIMAL (6, 2)  NULL,
    [Srok]         INT             NOT NULL,
    [Fact]         MONEY           NULL,
    [OurID]        TINYINT         NULL,
    [Pko]          TINYINT         NULL,
    [man_id]       TINYINT         NULL,
    [BankId]       TINYINT         NULL,
    [Tovchk]       TINYINT         NULL,
    [Frizer]       TINYINT         NULL,
    [Ag_Id]        TINYINT         NULL,
    [StfNom]       VARCHAR (6)     NULL,
    [StfDate]      DATETIME        NULL,
    [Qtyfriz]      INT             NULL,
    [Remark]       VARCHAR (50)    NULL,
    [Printed]      TINYINT         NULL,
    [Marsh]        INT             NULL,
    [BoxQty]       DECIMAL (8, 2)  NULL,
    [Weight]       DECIMAL (8, 2)  NULL,
    [Actn]         TINYINT         NULL,
    [CK]           TINYINT         NULL,
    [Tara]         TINYINT         NULL,
    [RefDatnom]    INT             NOT NULL,
    [MarshDay]     TINYINT         NULL,
    [Sk50prn]      TINYINT         NULL,
    [SPice]        MONEY           NULL,
    [SCice]        MONEY           NULL,
    [Izmen]        MONEY           NULL,
    [Back]         MONEY           NULL,
    [SpPF]         MONEY           NULL,
    [ScPF]         MONEY           NULL,
    [SpOther]      MONEY           NULL,
    [ScOther]      MONEY           NULL,
    [Done]         BIT             NULL,
    [Tomorrow]     BIT             NULL,
    [RemarkOp]     VARCHAR (50)    NULL,
    [Marsh2]       TINYINT         NULL,
    [Ready]        BIT             NULL,
    [DelivCancel]  BIT             NULL,
    [DayShift]     TINYINT         NULL,
    [PrintedNak]   TINYINT         NULL,
    [NeedCK]       BIT             NULL,
    [SertifDoc]    INT             NULL,
    [SPE]          DECIMAL (10, 2) NULL,
    [DeltaSpecSC]  DECIMAL (9, 2)  NULL,
    [TimeArrival]  CHAR (5)        NULL,
    [BruttoWeight] DECIMAL (12, 3) NULL,
    [TranspRashod] DECIMAL (10, 2) NULL,
    [Comp]         VARCHAR (12)    NULL,
    [SertND]       DATETIME        NULL,
    [SertNo]       VARCHAR (40)    NULL,
    [Sk50present]  BIT             NULL,
    [DCK]          INT             NULL,
    [B_Id2]        INT             NULL
);

