CREATE TABLE [dbo].[BitArray] (
    [Num] INT NOT NULL,
    [B10] BIT DEFAULT ((0)) NULL,
    [B9]  BIT DEFAULT ((0)) NULL,
    [B8]  BIT CONSTRAINT [DF__BitArray__B8__3D94C0AA] DEFAULT ((0)) NULL,
    [B7]  BIT CONSTRAINT [DF__BitArray__B7__35F39EE2] DEFAULT ((0)) NULL,
    [B6]  BIT CONSTRAINT [DF__BitArray__B6__36E7C31B] DEFAULT ((0)) NULL,
    [B5]  BIT CONSTRAINT [DF__BitArray__B5__37DBE754] DEFAULT ((0)) NULL,
    [B4]  BIT CONSTRAINT [DF__BitArray__B4__38D00B8D] DEFAULT ((0)) NULL,
    [B3]  BIT CONSTRAINT [DF__BitArray__B3__39C42FC6] DEFAULT ((0)) NULL,
    [B2]  BIT CONSTRAINT [DF__BitArray__B2__3AB853FF] DEFAULT ((0)) NULL,
    [B1]  BIT CONSTRAINT [DF__BitArray__B1__3BAC7838] DEFAULT ((0)) NULL,
    [B0]  BIT CONSTRAINT [DF__BitArray__B0__3CA09C71] DEFAULT ((0)) NULL,
    CONSTRAINT [BitArray_pk] PRIMARY KEY CLUSTERED ([Num] ASC)
);

