CREATE TABLE [dbo].[DefContract_backup2] (
    [DCK]                 INT             NOT NULL,
    [ND]                  DATETIME        DEFAULT (getdate()) NULL,
    [OP]                  INT             NULL,
    [Actual]              BIT             DEFAULT ((1)) NULL,
    [Our_id]              INT             DEFAULT ((0)) NOT NULL,
    [ContrTip]            INT             NULL,
    [pin]                 INT             NULL,
    [ContrName]           VARCHAR (80)    NULL,
    [ContrMain]           BIT             DEFAULT ((0)) NULL,
    [ContrNum]            VARCHAR (50)    NULL,
    [ContrDate]           DATETIME        NULL,
    [ContrEvalDate]       DATETIME        NULL,
    [Srok]                INT             DEFAULT ((0)) NOT NULL,
    [BnFlag]              BIT             DEFAULT ((0)) NULL,
    [NDS]                 BIT             DEFAULT ((0)) NULL,
    [minOrder]            NUMERIC (10, 3) NULL,
    [maxDaysOrder]        INT             NULL,
    [LastSver]            DATETIME        NULL,
    [Remark]              VARCHAR (200)   NULL,
    [gpOur_ID]            TINYINT         NULL,
    [Bank_ID]             INT             NULL,
    [p_id]                INT             DEFAULT ((0)) NULL,
    [limit]               MONEY           DEFAULT ((100000)) NOT NULL,
    [Extra]               FLOAT (53)      NULL,
    [wostamp]             BIT             NULL,
    [DCKOld]              INT             NULL,
    [PrevP_id]            INT             DEFAULT ((0)) NULL,
    [AccountID]           INT             NULL,
    [ag_id]               INT             DEFAULT ((0)) NOT NULL,
    [PrevAg_ID]           INT             NULL,
    [NeedFrizSver]        BIT             DEFAULT ((0)) NOT NULL,
    [LastFrizSver]        DATETIME        NULL,
    [Degust]              INT             DEFAULT ((0)) NULL,
    [dcnID]               INT             NULL,
    [DckMaster]           INT             DEFAULT ((0)) NULL,
    [NeedCK]              BIT             DEFAULT ((0)) NULL,
    [Factoring]           BIT             DEFAULT ((0)) NULL,
    [PrintStandartPhrase] BIT             DEFAULT ((0)) NULL,
    [Ncod]                INT             DEFAULT ((0)) NULL,
    [ExpressSver]         DATETIME        NULL,
    [Disab]               BIT             DEFAULT ((0)) NULL,
    [Debit]               BIT             DEFAULT ((0)) NULL,
    [gpBank_ID]           INT             DEFAULT ((8)) NULL,
    [FMonDisab]           BIT             DEFAULT ((0)) NULL,
    [TaxMID]              INT             DEFAULT ((0)) NULL,
    [PricePrecision]      SMALLINT        DEFAULT ((2)) NULL,
    [GPAccountID]         INT             DEFAULT ((1)) NOT NULL,
    [Old_DCK]             INT             NULL,
    UNIQUE NONCLUSTERED ([DCK] ASC)
);

