CREATE TABLE [dbo].[defcontract_back22feb] (
    [DCK]                 INT             IDENTITY (1, 1) NOT NULL,
    [ND]                  DATETIME        NULL,
    [OP]                  INT             NULL,
    [Actual]              BIT             NULL,
    [Our_id]              INT             NOT NULL,
    [ContrTip]            INT             NULL,
    [pin]                 INT             NULL,
    [ContrName]           VARCHAR (80)    NULL,
    [ContrMain]           BIT             NULL,
    [ContrNum]            VARCHAR (50)    NULL,
    [ContrDate]           DATETIME        NULL,
    [ContrEvalDate]       DATETIME        NULL,
    [Srok]                INT             NOT NULL,
    [BnFlag]              BIT             NULL,
    [NDS]                 BIT             NULL,
    [minOrder]            NUMERIC (10, 3) NULL,
    [maxDaysOrder]        INT             NULL,
    [LastSver]            DATETIME        NULL,
    [Remark]              VARCHAR (200)   NULL,
    [gpOur_ID]            TINYINT         NULL,
    [Bank_ID]             INT             NULL,
    [p_id]                INT             NULL,
    [limit]               MONEY           NOT NULL,
    [Extra]               FLOAT (53)      NULL,
    [wostamp]             BIT             NULL,
    [DCKOld]              INT             NULL,
    [PrevP_id]            INT             NULL,
    [AccountID]           INT             NULL,
    [ag_id]               INT             NOT NULL,
    [PrevAg_ID]           INT             NULL,
    [NeedFrizSver]        BIT             NOT NULL,
    [LastFrizSver]        DATETIME        NULL,
    [Degust]              INT             NULL,
    [dcnID]               INT             NULL,
    [DckMaster]           INT             NULL,
    [NeedCK]              BIT             NULL,
    [Factoring]           BIT             NULL,
    [PrintStandartPhrase] BIT             NULL,
    [Ncod]                INT             NULL,
    [ExpressSver]         DATETIME        NULL,
    [Disab]               BIT             NULL,
    [Debit]               BIT             NULL,
    [gpBank_ID]           INT             NULL,
    [FMonDisab]           BIT             NULL,
    [TaxMID]              INT             NULL,
    [PricePrecision]      SMALLINT        NULL,
    [GPAccountID]         INT             NOT NULL,
    [Old_DCK]             INT             NULL
);

