CREATE TABLE [dbo].[EMBT_CODE_ANA_PARAMS] (
    [RUNID]        NUMERIC (18)  NOT NULL,
    [UNIT_NUMBER]  NUMERIC (18)  NOT NULL,
    [PARAM_NUMBER] NUMERIC (18)  NOT NULL,
    [PARAM_VALUE]  VARCHAR (255) NULL,
    [DEFAULT_VAL]  INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([RUNID] ASC, [UNIT_NUMBER] ASC, [PARAM_NUMBER] ASC),
    FOREIGN KEY ([RUNID], [UNIT_NUMBER]) REFERENCES [dbo].[EMBT_CODE_ANA_UNITS] ([RUNID], [UNIT_NUMBER])
);


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EMBT_CODE_ANA_PARAMS] TO PUBLIC
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EMBT_CODE_ANA_PARAMS] TO PUBLIC
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EMBT_CODE_ANA_PARAMS] TO PUBLIC
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EMBT_CODE_ANA_PARAMS] TO PUBLIC
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[EMBT_CODE_ANA_PARAMS] TO PUBLIC
    AS [dbo];

