CREATE TABLE [dbo].[EMBT_CODE_ANA_DATA] (
    [RUNID]        NUMERIC (18) NOT NULL,
    [UNIT_NUMBER]  NUMERIC (18) NOT NULL,
    [LINE#]        NUMERIC (18) NOT NULL,
    [TOTAL_OCCUR]  NUMERIC (18) NULL,
    [TOTAL_TIME]   DECIMAL (28) NULL,
    [MIN_TIME]     DECIMAL (28) NULL,
    [MAX_TIME]     DECIMAL (28) NULL,
    [RELATED_UNIT] NUMERIC (18) NULL,
    PRIMARY KEY NONCLUSTERED ([RUNID] ASC, [UNIT_NUMBER] ASC, [LINE#] ASC),
    CHECK ('LINE#' IS NOT NULL),
    FOREIGN KEY ([RUNID]) REFERENCES [dbo].[EMBT_CODE_ANA_RUNS] ([RUNID]),
    FOREIGN KEY ([RUNID], [UNIT_NUMBER]) REFERENCES [dbo].[EMBT_CODE_ANA_UNITS] ([RUNID], [UNIT_NUMBER])
);


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EMBT_CODE_ANA_DATA] TO PUBLIC
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EMBT_CODE_ANA_DATA] TO PUBLIC
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EMBT_CODE_ANA_DATA] TO PUBLIC
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EMBT_CODE_ANA_DATA] TO PUBLIC
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[EMBT_CODE_ANA_DATA] TO PUBLIC
    AS [dbo];

