CREATE TABLE [dbo].[EMBT_CODE_ANA_RUNS] (
    [RUNID]               NUMERIC (18)  IDENTITY (1, 1) NOT NULL,
    [RUN_LOGIN]           VARCHAR (32)  NULL,
    [RUN_OWNER]           VARCHAR (32)  NULL,
    [RUN_DATE]            DATETIME      NULL,
    [RUN_COMMENT]         VARCHAR (255) NULL,
    [TOTAL_PROFILED_TIME] DECIMAL (28)  NOT NULL,
    [TOTAL_RUN_TIME]      DECIMAL (28)  NOT NULL,
    [SCHEDULED]           VARCHAR (255) DEFAULT ('') NOT NULL,
    PRIMARY KEY NONCLUSTERED ([RUNID] ASC)
);


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EMBT_CODE_ANA_RUNS] TO PUBLIC
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EMBT_CODE_ANA_RUNS] TO PUBLIC
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EMBT_CODE_ANA_RUNS] TO PUBLIC
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EMBT_CODE_ANA_RUNS] TO PUBLIC
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[EMBT_CODE_ANA_RUNS] TO PUBLIC
    AS [dbo];

