CREATE TABLE [dbo].[EMBT_CODE_ANA_UNITS] (
    [RUNID]          NUMERIC (18) NOT NULL,
    [UNIT_NUMBER]    NUMERIC (18) NOT NULL,
    [UNIT_TYPE]      VARCHAR (32) NULL,
    [UNIT_OWNER]     VARCHAR (32) NULL,
    [UNIT_DATABASE]  VARCHAR (32) NULL,
    [UNIT_NAME]      VARCHAR (32) NULL,
    [UNIT_TIMESTAMP] DATETIME     NULL,
    [TOTAL_TIME]     DECIMAL (28) DEFAULT ((0)) NOT NULL,
    [UNIT_SCOPE]     INT          NULL,
    PRIMARY KEY NONCLUSTERED ([RUNID] ASC, [UNIT_NUMBER] ASC),
    CHECK ('TOTAL_TIME' IS NOT NULL),
    FOREIGN KEY ([RUNID]) REFERENCES [dbo].[EMBT_CODE_ANA_RUNS] ([RUNID])
);


GO
GRANT UPDATE
    ON OBJECT::[dbo].[EMBT_CODE_ANA_UNITS] TO PUBLIC
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[EMBT_CODE_ANA_UNITS] TO PUBLIC
    AS [dbo];


GO
GRANT REFERENCES
    ON OBJECT::[dbo].[EMBT_CODE_ANA_UNITS] TO PUBLIC
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[EMBT_CODE_ANA_UNITS] TO PUBLIC
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[EMBT_CODE_ANA_UNITS] TO PUBLIC
    AS [dbo];

