CREATE TABLE [dbo].[FrizRequestLog] (
    [rid]           INT            IDENTITY (1, 1) NOT NULL,
    [rcmplxid]      INT            NULL,
    [rdt]           DATETIME       NULL,
    [rneedact]      INT            NULL,
    [rdepid]        INT            NULL,
    [rqty]          INT            NULL,
    [rnazn]         INT            NULL,
    [rreasonact]    INT            NULL,
    [rtpcode]       INT            NULL,
    [rtpaddr]       VARCHAR (300)  NULL,
    [rtpcontact]    VARCHAR (40)   NULL,
    [rtpcontactd]   VARCHAR (40)   NULL,
    [rtpphone]      VARCHAR (50)   NULL,
    [rtpag_id]      INT            NULL,
    [rtpag_phone]   VARCHAR (50)   NULL,
    [ractdate]      DATETIME       NULL,
    [rexecdate]     DATETIME       NULL,
    [rohocomm]      VARCHAR (1000) NULL,
    [radmcomm]      VARCHAR (1000) NULL,
    [rinvnom]       VARCHAR (100)  NULL,
    [rdatebefore]   BIT            NULL,
    [rstatus]       INT            NULL,
    [rsost]         INT            NULL,
    [rother]        VARCHAR (300)  NULL,
    [rprim]         VARCHAR (300)  NULL,
    [rdel]          VARCHAR (1)    CONSTRAINT [DF__FrizReques__rdel__1CF2E6EE_FrizRequestLog] DEFAULT ((0)) NULL,
    [ruin]          INT            NULL,
    [rbrand]        INT            NULL,
    [rfrizertip]    INT            NULL,
    [rtpcode2]      INT            NULL,
    [rtpaddr2]      VARCHAR (300)  NULL,
    [rtpcontact2]   VARCHAR (40)   NULL,
    [rtpcontactd2]  VARCHAR (40)   NULL,
    [rtpphone2]     VARCHAR (50)   NULL,
    [rtpag_id2]     INT            NULL,
    [rtpag_phone2]  VARCHAR (50)   NULL,
    [rdop]          VARCHAR (300)  NULL,
    [rmorozhstatus] INT            NULL,
    [rmorozhcomm]   VARCHAR (1000) NULL,
    [rfordoc]       INT            CONSTRAINT [DF__FrizReque__rford__05DA776C_FrizRequestLog] DEFAULT ((0)) NULL,
    [p_id]          INT            NULL,
    [operator]      INT            NULL,
    [opertip]       VARCHAR (3)    NULL,
    [operdate]      DATETIME       NULL,
    UNIQUE NONCLUSTERED ([rid] ASC)
);

