CREATE TABLE [dbo].[KassaN] (
    [KassID]      INT          IDENTITY (1, 1) NOT NULL,
    [nd]          DATETIME     NULL,
    [tm]          CHAR (8)     NULL,
    [Oper]        INT          NULL,
    [Act]         VARCHAR (4)  NULL,
    [SourDate]    DATETIME     NULL,
    [Nnak]        INT          NULL,
    [Plata]       MONEY        DEFAULT ((0)) NOT NULL,
    [Fam]         VARCHAR (40) NULL,
    [P_ID]        INT          NULL,
    [B_ID]        INT          NULL,
    [V_ID]        INT          NULL,
    [Ncod]        INT          NULL,
    [Remark]      VARCHAR (60) NULL,
    [RashFlag]    INT          NULL,
    [LostFlag]    INT          NULL,
    [LastFlag]    TINYINT      NULL,
    [Op]          INT          NULL,
    [Bank_ID]     INT          NULL,
    [Our_ID]      INT          NULL,
    [BankDay]     DATETIME     NULL,
    [Actn]        TINYINT      DEFAULT ((0)) NULL,
    [Ck]          TINYINT      NULL,
    [Thr]         INT          NULL,
    [ThrFam]      VARCHAR (40) NULL,
    [DocNom]      INT          NULL,
    [OrigRecn]    INT          NULL,
    [ForPrint]    TINYINT      DEFAULT ((1)) NULL,
    [SourDatNom]  INT          NULL,
    [StNom]       INT          NULL,
    [FromBank_ID] SMALLINT     DEFAULT ((0)) NULL,
    [SkladNo]     INT          NULL,
    [p_id1]       INT          NULL
);

