CREATE TABLE [dbo].[NC2] (
    [DatNom]       INT             NOT NULL,
    [ND]           DATETIME        NULL,
    [B_ID]         INT             NOT NULL,
    [Fam]          VARCHAR (35)    NULL,
    [TM]           CHAR (8)        NULL,
    [Op]           INT             NULL,
    [SP]           MONEY           CONSTRAINT [DF__NC__SP__52A420D22] DEFAULT ((0)) NOT NULL,
    [SC]           MONEY           CONSTRAINT [DF__NC__SC__5398450B2] DEFAULT ((0)) NOT NULL,
    [Extra]        DECIMAL (6, 2)  NULL,
    [Srok]         INT             CONSTRAINT [DF__NC__Srok__51AFFC992] DEFAULT ((0)) NOT NULL,
    [Fact]         MONEY           CONSTRAINT [DF__NC_2_Fact__04DA9AE4_NC_22] DEFAULT ((0)) NULL,
    [OurID]        TINYINT         NULL,
    [Pko]          TINYINT         CONSTRAINT [DF__NC_2_Pko__4830B400_NC_22] DEFAULT ((0)) NULL,
    [man_id]       TINYINT         NULL,
    [BankId]       TINYINT         CONSTRAINT [DF__NC_2_BankId__4924D839_NC_22] DEFAULT ((0)) NULL,
    [Tovchk]       TINYINT         CONSTRAINT [DF__NC_2_Tovchk__4A18FC72_NC_22] DEFAULT ((0)) NULL,
    [Frizer]       TINYINT         CONSTRAINT [DF__NC_2_Frizer__4B0D20AB_NC_22] DEFAULT ((0)) NULL,
    [Ag_Id]        TINYINT         NULL,
    [StfNom]       VARCHAR (6)     NULL,
    [StfDate]      DATETIME        NULL,
    [Qtyfriz]      INT             NULL,
    [Remark]       VARCHAR (50)    NULL,
    [Printed]      TINYINT         CONSTRAINT [DF__NC_2_Printed__4C0144E4_NC_22] DEFAULT ((0)) NULL,
    [Marsh]        INT             NULL,
    [BoxQty]       DECIMAL (8, 2)  NULL,
    [Weight]       DECIMAL (8, 2)  NULL,
    [Actn]         TINYINT         CONSTRAINT [DF__NC__Actn__3A827E7E2] DEFAULT ((0)) NULL,
    [CK]           TINYINT         NULL,
    [Tara]         TINYINT         CONSTRAINT [DF__NC__Tara__19E0A4C22] DEFAULT ((0)) NULL,
    [RefDatnom]    INT             CONSTRAINT [DF__NC_2_RefDatnom__4CF5691D_NC_22] DEFAULT ((0)) NOT NULL,
    [MarshDay]     TINYINT         NULL,
    [Sk50prn]      TINYINT         NULL,
    [SPice]        MONEY           CONSTRAINT [DF__NC_2_SPice__7C3A67EB_NC_22] DEFAULT ((0)) NULL,
    [SCice]        MONEY           CONSTRAINT [DF__NC_2_SCice__7D2E8C24_NC_22] DEFAULT ((0)) NULL,
    [Izmen]        MONEY           CONSTRAINT [DF__NC__Izmen__4FC7B4272] DEFAULT ((0)) NULL,
    [Back]         MONEY           CONSTRAINT [DF__NC__Back__50BBD8602] DEFAULT ((0)) NULL,
    [SpPF]         MONEY           CONSTRAINT [DF__NC_2_SpPF__5D8BC399_NC_22] DEFAULT ((0)) NULL,
    [ScPF]         MONEY           CONSTRAINT [DF__NC_2_ScPF__5E7FE7D2_NC_22] DEFAULT ((0)) NULL,
    [SpOther]      MONEY           CONSTRAINT [DF__NC_2_SpOther__774B959C_NC_22] DEFAULT ((0)) NULL,
    [ScOther]      MONEY           CONSTRAINT [DF__NC_2_ScOther__783FB9D5_NC_22] DEFAULT ((0)) NULL,
    [Done]         BIT             CONSTRAINT [DF__NC_2_Done__03B16C81_NC_22] DEFAULT ((0)) NULL,
    [Tomorrow]     BIT             CONSTRAINT [DF__NC_2_tomorrow__04A590BA_NC_22] DEFAULT ((0)) NULL,
    [RemarkOp]     VARCHAR (50)    NULL,
    [Marsh2]       TINYINT         CONSTRAINT [DF__NC__Marsh2__35BDC9621] DEFAULT ((0)) NULL,
    [Ready]        BIT             NULL,
    [DelivCancel]  BIT             CONSTRAINT [DF__NC__DelivCancel__18EC80892] DEFAULT ((0)) NULL,
    [DayShift]     TINYINT         CONSTRAINT [DF__NC__DayShift__5D96B021] DEFAULT ((0)) NULL,
    [PrintedNak]   TINYINT         CONSTRAINT [DF__NC__PrintedNak__7D0F5BE2A] DEFAULT ((0)) NULL,
    [NeedCK]       BIT             CONSTRAINT [DF__NC__NeedCK__1F2F69C42] DEFAULT ((0)) NULL,
    [SertifDoc]    INT             CONSTRAINT [DF__NC__SertifDoc__789FAC828] DEFAULT ((0)) NULL,
    [SPE]          DECIMAL (10, 2) CONSTRAINT [DF__NC__SPE__388527723] DEFAULT ((1.11)) NULL,
    [DeltaSpecSC]  DECIMAL (9, 2)  CONSTRAINT [DF__NC__DeltaSpecSC__3BB699D92] DEFAULT ((0)) NULL,
    [TimeArrival]  CHAR (5)        CONSTRAINT [DF__NC__TimeArrival__0C919629C] DEFAULT ('00:00') NULL,
    [BruttoWeight] DECIMAL (12, 3) NULL,
    [TranspRashod] DECIMAL (10, 2) NULL,
    [Comp]         VARCHAR (12)    NULL,
    CONSTRAINT [NC_pk2] PRIMARY KEY CLUSTERED ([DatNom] ASC)
);

