CREATE TABLE [dbo].[nvzakaz_log] (
    [nzid]      INT             NOT NULL,
    [datnom]    BIGINT          NULL,
    [Hitag]     INT             NULL,
    [Zakaz]     DECIMAL (10, 3) NULL,
    [Done]      BIT             NULL,
    [ND]        DATE            NULL,
    [Price]     MONEY           NULL,
    [Cost]      MONEY           NULL,
    [comp]      VARCHAR (256)   NULL,
    [tm]        VARCHAR (8)     NOT NULL,
    [tmEnd]     VARCHAR (8)     NULL,
    [curWeight] DECIMAL (10, 3) NULL,
    [tekWeight] DECIMAL (10, 3) NULL,
    [dt]        DATETIME        NULL,
    [dtEnd]     DATETIME        NULL,
    [ID]        INT             NULL,
    [Remark]    VARCHAR (50)    NOT NULL,
    [skladNo]   INT             NULL,
    [OP]        INT             NULL,
    [spk]       INT             NULL,
    [AuthorOP]  INT             NOT NULL,
    [NewDatnom] BIGINT          NULL,
    [TimeLog]   VARCHAR (10)    DEFAULT (CONVERT([varchar](10),getdate(),(108))) NOT NULL,
    [DateLog]   VARCHAR (10)    DEFAULT (CONVERT([varchar](10),getdate(),(104))) NOT NULL,
    [ActionLog] VARCHAR (3)     NULL,
    [CompLog]   VARCHAR (50)    DEFAULT (host_name()) NOT NULL,
    [AppLog]    VARCHAR (50)    DEFAULT (app_name()) NOT NULL,
    [LogID]     INT             IDENTITY (1, 1) NOT NULL
);

