CREATE TABLE [dbo].[PromoReq] (
    [id]                       INT             IDENTITY (1, 1) NOT NULL,
    [operator]                 INT             NULL,
    [create_date]              DATETIME        NULL,
    [act_date]                 DATETIME        NULL,
    [act_time]                 VARCHAR (50)    NULL,
    [agent_p_id]               INT             NULL,
    [tradepoint_id]            INT             NULL,
    [promotarget]              INT             NULL,
    [agent_phone]              VARCHAR (50)    NULL,
    [promomeh]                 VARCHAR (120)   NULL,
    [vol_tradepoint]           NUMERIC (10, 2) NULL,
    [vol_morozko]              NUMERIC (10, 2) NULL,
    [vol_morozko_after]        NUMERIC (10, 2) NULL,
    [vol_morozko_after_action] NUMERIC (10, 2) NULL,
    [concact]                  VARCHAR (300)   NULL,
    [depchief]                 INT             NULL,
    [tradem]                   INT             NULL,
    [act_2days]                BIT             CONSTRAINT [DF__PromoReq__act_2d__222C9D57] DEFAULT ((0)) NULL,
    [promouters]               VARCHAR (300)   NULL,
    [bonusnaklnum]             INT             NULL,
    [bonusnd]                  DATETIME        NULL,
    [bonuscontragentnaim]      VARCHAR (200)   NULL,
    [promomeh2]                VARCHAR (120)   NULL,
    [promostat]                INT             CONSTRAINT [DF__PromoReq__promos__37E6D44C] DEFAULT ((1)) NULL,
    [depchiefstat]             INT             CONSTRAINT [DF__PromoReq__depchi__38DAF885] DEFAULT ((-1)) NULL,
    [trademarketstat]          INT             CONSTRAINT [DF__PromoReq__tradem__39CF1CBE] DEFAULT ((-1)) NULL,
    [depchiefprim]             VARCHAR (100)   NULL,
    [trademarketprim]          VARCHAR (100)   NULL,
    [actprodano]               VARCHAR (50)    NULL,
    [actvidano]                VARCHAR (50)    NULL,
    [promoperszatr]            VARCHAR (50)    NULL,
    [actfinish]                INT             CONSTRAINT [DF__PromoReq__actfin__226C9479] DEFAULT ((-1)) NULL,
    [catmanager]               INT             NULL,
    [catmanagerstat]           INT             CONSTRAINT [DF__PromoReq__catman__0E508D33] DEFAULT ((-1)) NULL,
    [catmanagerprim]           VARCHAR (100)   NULL,
    [promotarget_sum]          NUMERIC (10, 2) NULL,
    UNIQUE NONCLUSTERED ([id] ASC)
);

