CREATE TABLE [dbo].[tdNC] (
    [nd]       DATETIME       NULL,
    [nnak]     INT            NOT NULL,
    [b_id]     INT            NULL,
    [fam]      VARCHAR (30)   NULL,
    [tm]       CHAR (8)       NULL,
    [op]       INT            NULL,
    [sp]       MONEY          NULL,
    [sc]       MONEY          NULL,
    [extra]    DECIMAL (8, 2) NULL,
    [srok]     INT            NULL,
    [our_id]   TINYINT        NULL,
    [Pko]      BIT            NULL,
    [man_id]   INT            NULL,
    [bank]     BIT            NULL,
    [tovchk]   BIT            NULL,
    [frizer]   BIT            NULL,
    [met]      BIT            DEFAULT (0) NULL,
    [ag_id]    INT            NULL,
    [stfnom]   VARCHAR (6)    NULL,
    [stfdate]  DATETIME       NULL,
    [tomorrow] BIT            NULL,
    [qtyfriz]  INT            NULL,
    [Att]      BIT            DEFAULT (0) NULL,
    [Ready]    BIT            DEFAULT (0) NULL,
    [Remark]   VARCHAR (50)   NULL,
    [Printed]  BIT            NULL,
    [Marsh]    INT            NULL,
    [MarshNom] INT            NULL,
    [BoxQty]   DECIMAL (8, 2) NULL,
    [Weight]   FLOAT (53)     NULL,
    [Actn]     BIT            DEFAULT (0) NULL,
    [CK]       BIT            DEFAULT (0) NULL,
    [Tara]     BIT            DEFAULT (0) NULL,
    [Comp]     VARCHAR (16)   NULL,
    [RefDate]  DATETIME       NULL,
    [RefNnak]  INT            NULL,
    [MarshDay] INT            NULL,
    [Sk50prn]  BIT            DEFAULT (0) NULL,
    [Done]     BIT            DEFAULT (0) NULL,
    [IDtp]     VARCHAR (15)   NULL,
    [izmen]    MONEY          NULL
);

