CREATE TABLE [NearLogistic].[nlMarshList] (
    [Weight]              FLOAT (53)      NULL,
    [WayPay]              MONEY           NULL,
    [VetPay]              MONEY           NULL,
    [VedNabPrinted]       INT             NULL,
    [V_idTr]              INT             NULL,
    [V_ID]                INT             NULL,
    [TmCallDrv]           CHAR (5)        NULL,
    [TimeStart]           CHAR (5)        NULL,
    [TimePlan]            CHAR (5)        NULL,
    [TimePhoneCall]       CHAR (5)        NULL,
    [TimeGo]              DATETIME        NULL,
    [TimeFinish]          CHAR (5)        NULL,
    [TimeBack]            DATETIME        NULL,
    [SpedDrID]            INT             NULL,
    [SelfShip]            BIT             NULL,
    [ScanND]              DATETIME        NULL,
    [RtnTovFlg]           BIT             NULL,
    [Remark]              VARCHAR (100)   NULL,
    [Peni]                FLOAT (53)      NULL,
    [NotifyDrvTime]       VARCHAR (5)     NULL,
    [nlTariffParamsIDSpd] INT             NULL,
    [nlTariffParamsIDDrv] INT             NULL,
    [ND]                  DATETIME        NULL,
    [MStatus]             INT             NULL,
    [mState]              INT             NULL,
    [MoneyBack]           BIT             NULL,
    [Marsh]               INT             NULL,
    [Marja]               MONEY           NULL,
    [ListNoSped]          INT             NULL,
    [ListNo]              INT             NULL,
    [LgsId]               INT             NULL,
    [Km1]                 FLOAT (53)      NULL,
    [Km0]                 FLOAT (53)      NULL,
    [drId]                INT             NULL,
    [Dots]                INT             NULL,
    [dopWeight]           FLOAT (53)      NULL,
    [Dohod]               MONEY           NULL,
    [Dist]                FLOAT (53)      NULL,
    [Direction]           VARCHAR (150)   NULL,
    [CalcRashod]          FLOAT (53)      NULL,
    [CalcDist]            FLOAT (53)      NULL,
    [BruttoWeight]        DECIMAL (12, 2) NULL,
    [BoxQty]              FLOAT (53)      NULL,
    [AwayTime]            DATETIME        NULL
);

