CREATE TABLE [RetroB].[Kassa1] (
    [KassID]      INT             NULL,
    [nd]          DATETIME        NULL,
    [tm]          CHAR (8)        NULL,
    [Oper]        INT             NULL,
    [Act]         VARCHAR (4)     NULL,
    [SourDate]    DATETIME        NULL,
    [Nnak]        INT             NULL,
    [Plata]       MONEY           NULL,
    [Fam]         VARCHAR (40)    NULL,
    [P_ID]        INT             NULL,
    [B_ID]        INT             NULL,
    [V_ID]        INT             NULL,
    [Ncod]        INT             NULL,
    [Remark]      VARCHAR (60)    NULL,
    [RashFlag]    INT             NULL,
    [LostFlag]    INT             NULL,
    [LastFlag]    TINYINT         NULL,
    [Op]          INT             NULL,
    [Bank_ID]     INT             NULL,
    [Our_ID]      INT             NULL,
    [BankDay]     DATETIME        NULL,
    [Actn]        TINYINT         NULL,
    [Ck]          TINYINT         NULL,
    [Thr]         INT             NULL,
    [ThrFam]      VARCHAR (40)    NULL,
    [DocNom]      INT             NULL,
    [OrigRecn]    INT             NULL,
    [ForPrint]    TINYINT         NULL,
    [SourDatNom]  INT             NULL,
    [StNom]       INT             DEFAULT ((0)) NULL,
    [FromBank_ID] SMALLINT        DEFAULT ((0)) NULL,
    [SkladNo]     INT             NULL,
    [DepID]       INT             DEFAULT ((0)) NULL,
    [B_idPlat]    INT             NULL,
    [OperOld]     INT             NULL,
    [NDInp]       DATETIME        NULL,
    [InBank]      BIT             NULL,
    [Nalog]       NUMERIC (4, 2)  NULL,
    [RemarkPlat]  VARCHAR (100)   NULL,
    [pin]         INT             NULL,
    [platarez]    MONEY           NULL,
    [DCK]         INT             NULL,
    [KassaNo]     INT             NULL,
    [RealOper]    BIT             NULL,
    [Plata2]      DECIMAL (12, 2) NULL
);

