CREATE TABLE [Guard].[PlanExec3] (
    [Comp]            VARCHAR (30)    NULL,
    [b_id]            INT             NULL,
    [Plann]           BIT             NULL,
    [ag_id]           INT             NULL,
    [dt]              CHAR (5)        NULL,
    [BName]           VARCHAR (100)   NULL,
    [FactT]           CHAR (8)        NULL,
    [Tara]            INT             NULL,
    [Audit]           CHAR (8)        NULL,
    [AdvOrd]          CHAR (8)        NULL,
    [NeudSpr]         INT             NULL,
    [LastSver]        DATE            NULL,
    [LastSell]        DATE            NULL,
    [DayProd]         CHAR (20)       NULL,
    [Debt]            DECIMAL (12, 2) DEFAULT ((0)) NULL,
    [Overdue]         DECIMAL (12, 2) DEFAULT ((0)) NULL,
    [Over17]          DECIMAL (12, 2) DEFAULT ((0)) NULL,
    [Deep]            INT             NULL,
    [WeekSell]        DECIMAL (12, 2) NULL,
    [MonthSell]       DECIMAL (12, 2) NULL,
    [WeekPay]         DECIMAL (12, 2) NULL,
    [MonthPay]        DECIMAL (12, 2) NULL,
    [DepID]           INT             NULL,
    [sv_ag_id]        INT             NULL,
    [SuperFam]        VARCHAR (100)   NULL,
    [DayPay]          DECIMAL (10, 2) NULL,
    [FrizQty]         INT             NULL,
    [gpAddr]          VARCHAR (200)   NULL,
    [LastSverSVDate]  DATETIME        NULL,
    [LastSverSVState] INT             NULL,
    [Photos]          SMALLINT        DEFAULT ((0)) NULL,
    [AgentFam]        VARCHAR (100)   NULL,
    [TodaySell]       DECIMAL (12, 2) DEFAULT ((0)) NULL,
    [SkipT]           VARCHAR (8)     NULL,
    [Tip]             SMALLINT        DEFAULT ((0)) NULL
);

