CREATE TABLE [Guard].[Visual_Deb] (
    [id]         INT             NOT NULL,
    [startid]    INT             NULL,
    [ncom]       INT             NULL,
    [ncod]       INT             NULL,
    [datepost]   DATETIME        NULL,
    [price]      MONEY           NULL,
    [start]      DECIMAL (12, 3) NULL,
    [startthis]  DECIMAL (12, 3) NULL,
    [hitag]      INT             NULL,
    [sklad]      SMALLINT        NULL,
    [cost]       DECIMAL (13, 5) NULL,
    [nalog5]     TINYINT         DEFAULT ((0)) NULL,
    [minp]       INT             DEFAULT ((1)) NULL,
    [mpu]        INT             DEFAULT ((1)) NULL,
    [sert_id]    INT             NULL,
    [rang]       CHAR (1)        NULL,
    [now]        NUMERIC (8)     NULL,
    [isprav]     DECIMAL (12, 3) DEFAULT ((0)) NULL,
    [remov]      DECIMAL (12, 3) DEFAULT ((0)) NULL,
    [bad]        DECIMAL (12, 3) DEFAULT ((0)) NULL,
    [dater]      DATETIME        NULL,
    [srokh]      DATETIME        NULL,
    [country]    VARCHAR (15)    NULL,
    [rezerv]     DECIMAL (12, 3) NULL,
    [units]      VARCHAR (3)     NULL,
    [locked]     BIT             NULL,
    [ncountry]   DECIMAL (3)     NULL,
    [gtd]        VARCHAR (100)   NULL,
    [vitr]       DECIMAL (12, 3) DEFAULT ((0)) NULL,
    [our_id]     SMALLINT        DEFAULT ((7)) NULL,
    [weight]     DECIMAL (12, 3) DEFAULT ((0)) NULL,
    [baseprice]  MONEY           NULL,
    [LastDate]   DATETIME        NULL,
    [morn]       NUMERIC (6)     NULL,
    [sell]       NUMERIC (5)     NULL,
    [MeasId]     TINYINT         DEFAULT ((2)) NULL,
    [ncnt]       INT             NULL,
    [DCK]        INT             NULL,
    [wsid]       TINYINT         DEFAULT ((1)) NULL,
    [CountryID]  INT             NULL,
    [ProducerID] INT             NULL,
    [pin]        INT             NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

