CREATE TABLE [LoadData].[rez] (
    [MainParent] INT             NULL,
    [nd]         DATETIME        NULL,
    [tm]         CHAR (8)        NULL,
    [datnom]     INT             NULL,
    [srok]       INT             NULL,
    [sp]         MONEY           NULL,
    [hitag]      INT             NULL,
    [NAME]       VARCHAR (90)    NULL,
    [WEIGHT]     DECIMAL (12, 3) NULL,
    [baseei]     TINYINT         NULL,
    [netto]      DECIMAL (10, 3) NULL,
    [price]      NUMERIC (14, 5) NULL,
    [cost]       DECIMAL (14, 5) NULL,
    [b_id]       INT             NULL,
    [klient]     VARCHAR (255)   NULL,
    [tovar1]     VARCHAR (50)    NULL,
    [klient1]    VARCHAR (255)   NULL,
    [nettype]    NUMERIC (2)     NULL,
    [klient3]    VARCHAR (50)    NULL,
    [comp1]      VARCHAR (100)   NULL,
    [comp2]      VARCHAR (100)   NULL,
    [comp3]      VARCHAR (100)   NULL,
    [comp4]      VARCHAR (100)   NULL,
    [comp5]      VARCHAR (70)    NULL,
    [kod1]       SMALLINT        NULL,
    [kod2]       SMALLINT        NULL,
    [kod3]       SMALLINT        NULL,
    [kod4]       SMALLINT        NULL,
    [kod5]       INT             NULL,
    [depid]      INT             NULL,
    [dname]      VARCHAR (70)    NULL,
    [Ngrp]       INT             NULL,
    [KODDOG]     INT             NULL,
    [Dogovor]    VARCHAR (336)   NULL,
    [Oblast]     VARCHAR (50)    NULL,
    [Sklad]      SMALLINT        NULL,
    [SkladName]  VARCHAR (50)    NULL,
    [kol]        DECIMAL (12, 3) NULL,
    [Upak]       INT             NULL,
    [Zakup]      VARCHAR (70)    NULL,
    [KodDogVen]  INT             NULL,
    [DogName]    VARCHAR (50)    NULL,
    [Format]     VARCHAR (100)   NULL,
    [DocType]    VARCHAR (255)   NULL,
    [Nds]        TINYINT         NULL,
    [Ourname]    VARCHAR (60)    NULL,
    [GpAddr]     VARCHAR (255)   NULL,
    [ShipType]   VARCHAR (40)    NULL,
    [Exttag]     VARCHAR (20)    NULL,
    [flgWeight]  BIT             NULL,
    [VenPin]     INT             NULL,
    [InpCost]    DECIMAL (12, 4) NULL,
    [InpPrice]   DECIMAL (12, 4) NULL,
    [VbBaseCost] DECIMAL (10, 2) NULL
);

